/**
 * DTO (Data Transfer Object) and Command Model Type Definitions
 *
 * This file contains all type definitions for API requests and responses,
 * derived from database models defined in src/db/database.types.ts
 */

import type { Tables, TablesInsert, TablesUpdate } from "./db/database.types";

// ============================================================================
// Base Entity DTOs
// ============================================================================

/**
 * FlashcardDTO - Complete flashcard representation
 * Source: Database.public.Tables.flashcards.Row
 */
export type FlashcardDTO = Tables<"flashcards">;

/**
 * GenerationDTO - Complete generation metadata representation
 * Source: Database.public.Tables.generations.Row
 */
export type GenerationDTO = Tables<"generations">;

/**
 * GenerationErrorLogDTO - Error log representation
 * Source: Database.public.Tables.generation_error_logs.Row
 */
export type GenerationErrorLogDTO = Tables<"generation_error_logs">;

// ============================================================================
// Enums and Constants
// ============================================================================

/**
 * FlashcardSource - Valid source types for flashcards
 * - ai-full: Generated by AI without user edits
 * - ai-edited: Generated by AI and then edited by user
 * - manual: Created manually by user
 */
export type FlashcardSource = "ai-full" | "ai-edited" | "manual";

/**
 * SortOrder - Valid sort order values
 */
export type SortOrder = "asc" | "desc";

// ============================================================================
// Command Models - Flashcards
// ============================================================================

/**
 * CreateFlashcardDTO - Data required to create a single flashcard
 * Source: Derived from Database.public.Tables.flashcards.Insert
 *
 * Note: user_id is omitted as it's derived from authentication context
 * Note: id, created_at, updated_at are auto-generated by the database
 */
export type CreateFlashcardDTO = Pick<TablesInsert<"flashcards">, "front" | "back" | "source" | "generation_id">;

/**
 * CreateFlashcardsCommand - Request body for POST /flashcards
 * Allows creating multiple flashcards in a single request
 */
export interface CreateFlashcardsCommand {
  flashcards: CreateFlashcardDTO[];
}

/**
 * UpdateFlashcardDTO - Data for updating an existing flashcard
 * Source: Derived from Database.public.Tables.flashcards.Update
 *
 * All fields are optional to allow partial updates
 * Note: id, user_id, created_at, updated_at are not updatable via API
 */
export type UpdateFlashcardDTO = Pick<TablesUpdate<"flashcards">, "front" | "back" | "source" | "generation_id">;

/**
 * FlashcardProposalDTO - AI-generated flashcard proposal (before user acceptance)
 * Source: Derived from CreateFlashcardDTO
 *
 * Used in POST /generations response to return proposed flashcards
 * Does not include generation_id as it's set during acceptance
 */
export type FlashcardProposalDTO = Pick<CreateFlashcardDTO, "front" | "back" | "source">;

// ============================================================================
// Command Models - Generations
// ============================================================================

/**
 * CreateGenerationCommand - Request body for POST /generations
 * Initiates AI generation process
 *
 * Validation: source_text must be between 1000 and 10000 characters
 */
export interface CreateGenerationCommand {
  source_text: string;
}

// ============================================================================
// Pagination and Query Parameters
// ============================================================================

/**
 * PaginationDTO - Pagination metadata for list responses
 */
export interface PaginationDTO {
  page: number;
  limit: number;
  total: number;
}

/**
 * ListFlashcardsQuery - Query parameters for GET /flashcards
 * All parameters are optional with sensible defaults
 */
export interface ListFlashcardsQuery {
  page?: number;
  limit?: number;
  sort?: string;
  order?: SortOrder;
  source?: FlashcardSource;
  generation_id?: number;
}

/**
 * ListGenerationsQuery - Query parameters for GET /generations
 * All parameters are optional with sensible defaults
 */
export interface ListGenerationsQuery {
  page?: number;
  limit?: number;
}

// ============================================================================
// Response Types - Flashcards
// ============================================================================

/**
 * ListFlashcardsResponse - Response for GET /flashcards
 * Returns paginated list of flashcards
 */
export interface ListFlashcardsResponse {
  data: FlashcardDTO[];
  pagination: PaginationDTO;
}

/**
 * CreateFlashcardsResponse - Response for POST /flashcards
 * Returns created flashcards with generated IDs and timestamps
 */
export interface CreateFlashcardsResponse {
  flashcards: FlashcardDTO[];
}

/**
 * DeleteFlashcardResponse - Response for DELETE /flashcards/{id}
 * Confirms successful deletion
 */
export interface DeleteFlashcardResponse {
  message: string;
}

// ============================================================================
// Response Types - Generations
// ============================================================================

/**
 * CreateGenerationResponse - Response for POST /generations
 * Returns generation metadata and proposed flashcards
 *
 * User can then review proposals and accept/edit them via POST /flashcards
 */
export interface CreateGenerationResponse {
  generation_id: number;
  flashcards_proposals: FlashcardProposalDTO[];
  generated_count: number;
}

/**
 * ListGenerationsResponse - Response for GET /generations
 * Returns list of generation requests with optional pagination
 */
export interface ListGenerationsResponse {
  data: GenerationDTO[];
  pagination?: PaginationDTO;
}

/**
 * GetGenerationResponse - Response for GET /generations/{id}
 * Returns detailed generation info with associated flashcards
 */
export interface GetGenerationResponse {
  generation: GenerationDTO;
  flashcards: FlashcardDTO[];
}

// ============================================================================
// Response Types - Error Logs
// ============================================================================

/**
 * ListGenerationErrorLogsResponse - Response for GET /generation-error-logs
 * Returns list of error logs (typically for admin/debugging)
 */
export interface ListGenerationErrorLogsResponse {
  data: GenerationErrorLogDTO[];
}
